# Generated by Django 3.0.4 on 2020-03-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=50)),
                ('bank_id', models.TextField(null=True)),
                ('branch', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('district', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('bank_name', models.TextField(null=True)),
            ],
        ),
    ]
